name: Build and Push System Info Docker Image By Manifest

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short SHA
        id: vars
        run: echo "short_sha=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

      - name: Build and push amd64 image
        uses: docker/build-push-action@v6
        with:
          context: ./manifest
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/echo-system-info:manifest-amd64
            ${{ secrets.DOCKER_USERNAME }}/echo-system-info:manifest-amd64-${{ env.short_sha }}
          platforms: linux/amd64

      - name: Build and push arm64 image
        uses: docker/build-push-action@v6
        with:
          context: ./manifest
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/echo-system-info:manifest-arm64
            ${{ secrets.DOCKER_USERNAME }}/echo-system-info:manifest-arm64-${{ env.short_sha }}
          platforms: linux/arm64

      - uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/echo-system-info:manifest
            ${{ secrets.DOCKER_USERNAME }}/echo-system-info:manifest-${{ env.short_sha }}
          sources: |
            ${{ secrets.DOCKER_USERNAME }}/echo-system-info:manifest-amd64
            ${{ secrets.DOCKER_USERNAME }}/echo-system-info:manifest-arm64
